### ISSUE TITLE
node is not Working 

### ISSUE THREAD

**Issue by 1617176084** [Taco-Network/taco-blockchain#1]
![image](https://user-images.githubusercontent.com/7008899/125652096-87b4b55a-2554-4a8f-9512-50f2420371ce.png)

**Comment by Taco-Network** [comment]
try dns-introducer.taconetwork.net:18620

or here are some peers:
86.175.101.123:18620
211.22.218.17:18620
58.136.84.51:18620

**Comment by longnc84** [comment]
Still not sync…
