### ISSUE TITLE
installation has failed

### ISSUE THREAD

**Issue by Sheng-Go** [Taco-Network/taco-blockchain#2]
![安裝失敗](https://user-images.githubusercontent.com/87187522/125874830-29992012-3837-4f8e-aeab-f437eb93cda4.png)

**Comment by sergiosurvival** [comment]
![2021-07-16 (2)](https://user-images.githubusercontent.com/83919237/125948635-f61f0803-94d9-4be8-bc97-12a20276bcd9.png)

**Comment by sergiosurvival** [comment]
nosincroniza 0/0

**Comment by Taco-Network** [comment]
could you please post your log?

**Comment by jackymardt** [comment]
close your firewall or antivirus software, and reinstall
